# Generated by Django 4.2.1 on 2024-03-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # ('user_id', models.IntegerField(auto_created=True)),
                # ('first_name', models.CharField(max_length=50, null=True)),
                # ('last_name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=8, max_digits=25, null=True)),
                ('user_type', models.CharField(default='user', choices=[('user', 'User'), ('admin', 'Admin'), ('other', 'Other')], max_length=25)),
                ('createdby', models.IntegerField(default=99)),
                ('delete1', models.IntegerField(default=0)),
                ('status', models.CharField(default=1, choices=[('', '-SELECT ONE-'),('1', 'ACTIVE'),('0', 'IN-ACTIVE'),('2', 'PROCESS')],)),
                # ('status', models.IntegerField(default=1)),
                # STATUS_CHOICES = ( ('1', 'ACTIVE'),('0', 'IN-ACTIVE'),('2', 'PROCESS'),    )
                # status   = models.IntegerField(default='1', choices=STATUS_CHOICES) 
            ],
            options={
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),                
                ('from_currency', models.CharField(max_length=10, null=True,default='INR')),
                ('to_currency', models.CharField(max_length=10, null=True,default='INR')),
                ('from_val', models.FloatField(max_length=20, null=True,default=1)),
                ('to_val', models.FloatField(max_length=20, null=True,default=1)),
                ('delete1', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'currency_exchange',
            },
        ),
    ]
